FROM ghcr.io/oracle/oraclelinux:8-slim as build
ARG ARCH
ENV ARCH=$ARCH

COPY . /go/src/github.com/rancher/fleet/

RUN microdnf update -y --setopt=install_weak_deps=0 --setopt=tsflags=nodocs && \
    microdnf install -y golang-1.20.10-1.module+el8.9.0+90068+08775a1f.x86_64 && \
    microdnf install -y git && \
    cd /go/src/github.com/rancher/fleet/scripts && \
    ./build && \
    ./test

RUN groupadd -g 1000 fleet-apply && useradd -u 1000 -g 1000 -m fleet-apply

FROM ghcr.io/verrazzano/ol8-base:v0.0.1-20231102152128-e7afc807
ARG ARCH
ENV ARCH=$ARCH

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group

COPY --from=build /go/src/github.com/rancher/fleet/bin/fleetagent-linux-$ARCH /usr/bin/fleetagent
COPY --from=build /go/src/github.com/rancher/fleet/bin/fleet-linux-$ARCH /usr/bin/fleet
COPY package/log.sh /usr/bin/
COPY LICENSE README.md THIRD_PARTY_LICENSES.txt SECURITY.md /licenses/

CMD ["fleetagent"]
